---
# ✅ WEBSERVER-ONLY ROLE - No database dependencies
# Users choose their own database setup

# Only collections needed for webserver functionality
collections:
  - name: community.general
    version: ">=5.0.0"
  - name: ansible.posix
    version: ">=1.0.0"

# No role dependencies - database-agnostic approach
# roles: []

# For testing with complete stack, use separate requirements file
# See: molecule/*/requirements.yml for testing-specific dependencies
