---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: docker

platforms:
  - name: simple-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    published_ports:
      - "8183:80"

provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      stdout_callback: yaml

verifier:
  name: ansible
