---
# Tareas específicas para RedHat/CentOS/Rocky

- name: Instalar repositorio EPEL
  ansible.builtin.dnf:
    name: epel-release
    state: present
  tags: [packages, repo]

- name: Remover curl-minimal si existe (Rocky Linux fix)
  ansible.builtin.dnf:
    name: curl-minimal
    state: absent
  failed_when: false
  tags: [packages]

- name: Instalar paquetes necesarios para WordPress
  ansible.builtin.dnf:
    name: "{{ redhat_packages }}"
    state: present
  tags: [packages]

- name: Configure basic Apache for PHP (Rocky Linux)
  ansible.builtin.copy:
    content: |
      # Basic PHP configuration for Rocky Linux
      # Note: PHP-FPM requires manual configuration in containerized environments
      
      # Directory index with PHP priority
      <IfModule dir_module>
          DirectoryIndex index.php index.html index.htm
      </IfModule>
      
      # Basic MIME type for PHP files
      AddType application/x-httpd-php .php
      
      # Try to use mod_php if available (usually not in Rocky 9)
      <IfModule mod_php.c>
          <FilesMatch "\.php$">
              SetHandler application/x-httpd-php
          </FilesMatch>
      </IfModule>
      
      # Production note: Configure PHP-FPM manually for full functionality
    dest: /etc/httpd/conf.d/php-basic.conf
    mode: '0644'
    backup: true
  notify: restart httpd
  tags: [php]

- name: Configurar firewall para HTTP/HTTPS
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - http
    - https
  failed_when: false
  tags: [firewall]

- name: Configurar SELinux para WordPress (básico)
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
  failed_when: false
  tags: [selinux]

- name: Crear directorio de WordPress
  ansible.builtin.file:
    path: "{{ wordpress_install_dir }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_group }}"
    mode: "0755"
  tags: [wordpress, directories]
