---
# Verificaciones comunes para todos los hosts - con tests de idempotencia
- name: Verify all WordPress servers
  hosts: wordpress_servers
  become: true
  gather_facts: true
  tasks:
    - name: Check correct Apache service is running
      systemd:
        name: "{{ expected_apache_service }}"
        state: started
        enabled: yes
      check_mode: true
      register: apache_status
      failed_when: apache_status is changed

    - name: Check MySQL service is running
      systemd:
        name: "{{ expected_mysql_service }}"
        state: started
        enabled: yes
      check_mode: true
      register: mysql_status
      failed_when: mysql_status is changed

    # ✅ NEW: Test de idempotencia específico para Apache sites
    - name: Verify WordPress site is enabled (idempotent)
      ansible.builtin.stat:
        path: /etc/apache2/sites-enabled/wordpress.conf
      register: wp_site_enabled
      when: ansible_os_family == "Debian"

    - name: Verify default site is disabled (idempotent)
      ansible.builtin.stat:
        path: /etc/apache2/sites-enabled/000-default.conf
      register: default_site_status
      when: ansible_os_family == "Debian"

    - name: Assert WordPress site configuration is idempotent
      assert:
        that:
          - wp_site_enabled.stat.exists
          - not default_site_status.stat.exists
        fail_msg: "Apache site configuration is not idempotent"
        success_msg: "✅ Apache site configuration is idempotent"
      when: ansible_os_family == "Debian"

    - name: Check WordPress directory exists
      stat:
        path: /var/www/html/wordpress
      register: wp_dir
      failed_when: not wp_dir.stat.exists

    - name: Check wp-config.php exists and is configured
      lineinfile:
        path: /var/www/html/wordpress/wp-config.php
        line: "define( 'DB_NAME', 'test_wordpress_db' );"
        state: present
      check_mode: true
      register: db_config
      failed_when: db_config is changed

    # ✅ NEW: Test de idempotencia para archivos WordPress
    - name: Verify WordPress files are not re-downloaded (idempotent)
      stat:
        path: "{{ wordpress_install_dir }}/wp-config.php"
      register: wp_config_exists

    - name: Assert WordPress installation is idempotent
      assert:
        that:
          - wp_config_exists.stat.exists
          - wp_config_exists.stat.mode == "0644"
        fail_msg: "WordPress installation is not idempotent"
        success_msg: "✅ WordPress installation is idempotent"

    - name: Test database connection
      mysql_query:
        login_host: localhost
        login_user: test_wp_user
        login_password: test_wp_password
        login_db: test_wordpress_db
        query: "SELECT 1 as test_connection"
      register: db_test
      failed_when: db_test is failed

    - name: Verify PHP extensions are installed
      command: php -m
      register: php_modules
      changed_when: false
      failed_when: >
        'mysql' not in php_modules.stdout or
        'curl' not in php_modules.stdout or
        'gd' not in php_modules.stdout

    # ✅ NEW: Test HTTP response es consistente
    - name: Test HTTP response consistency (idempotent)
      uri:
        url: "http://localhost"
        method: GET
        status_code: [200, 301, 302, 404]
      register: http_response_1

    - name: Test HTTP response second time
      uri:
        url: "http://localhost"
        method: GET  
        status_code: [200, 301, 302, 404]
      register: http_response_2

    - name: Assert HTTP responses are consistent
      assert:
        that:
          - http_response_1.status == http_response_2.status
        fail_msg: "HTTP responses are inconsistent: {{ http_response_1.status }} vs {{ http_response_2.status }}"
        success_msg: "✅ HTTP responses are consistent ({{ http_response_1.status }})"

    - name: Final verification summary
      debug:
        msg:
          - "🎉 {{ inventory_hostname }} verification completed!"
          - "✅ Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "✅ PHP Version: {{ expected_php_version }}"
          - "✅ Apache Service: {{ expected_apache_service }}"
          - "✅ MySQL Service: {{ expected_mysql_service }}"
          - "✅ WordPress Domain: {{ wordpress_domain }}"
          - "✅ Database Connection: Working"
          - "✅ WordPress Files: Present"
          - "✅ Idempotence: Verified"
