---
- name: Converge Ubuntu
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Include wordpress_webserver role
      ansible.builtin.include_role:
        name: wordpress_webserver