---
- name: Converge Ubuntu
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Include wordpress_webserver role (relative path)
      ansible.builtin.include_role:
        name: "{{ playbook_dir | dirname | dirname | basename }}"
