---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Install Python MySQL connector for testing
      pip:
        name: PyMySQL
        state: present
        
    - name: Include role under test
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
