---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml  # Archivo en molecule/ubuntu/requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    published_ports:
      - "8180:80"

provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu-instance:
        mysql_root_password: "test_root_password"
        mysql_root_password_update: true
        mysql_user_password_update: true
        mysql_enabled_on_startup: true
        mysql_bind_address: '127.0.0.1'
        overwrite_global_mycnf: true
        
        mysql_databases:
          - name: "test_wordpress_db"
            encoding: utf8mb4
            collation: utf8mb4_unicode_ci
            state: present
            
        mysql_users:
          - name: "test_wp_user"
            host: "%"
            password: "test_wp_password"
            priv: "test_wordpress_db.*:ALL"
            state: present
            update_password: always
        
        wordpress_domain: "ubuntu-wordpress.test"
        wordpress_db_host: "localhost"
        wordpress_db_name: "test_wordpress_db"
        wordpress_db_user: "test_wp_user"
        wordpress_db_password: "test_wp_password"

verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence  # TEMPORAL: Deshabilitado
    - verify
    - cleanup
    - destroy
