---
- name: Verify Ubuntu
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Debug Ubuntu information
      debug:
        msg:
          - "🐧 Testing Ubuntu 22.04"
          - "Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Check if Apache is running
      systemd:
        name: apache2
        state: started
        enabled: yes
      check_mode: true
      register: apache_status
      failed_when: apache_status is changed

    - name: Check PHP version
      command: php --version
      register: php_version_output
      changed_when: false

    - name: Verify PHP 8.1 is installed
      assert:
        that:
          - "'PHP 8.1' in php_version_output.stdout"
        success_msg: "✅ PHP 8.1 detected: {{ php_version_output.stdout.split()[1] }}"

    - name: Check WordPress directory exists
      stat:
        path: /var/www/html/wordpress
      register: wp_dir
      failed_when: not wp_dir.stat.exists

    - name: Test HTTP response
      uri:
        url: "http://localhost"
        status_code: [200, 301, 302, 404]
      register: http_response

    - name: Test database connection
      mysql_query:
        login_host: localhost
        login_user: test_wp_user
        login_password: test_wp_password
        login_db: test_wordpress_db
        query: "SELECT 1 as test_connection"

    - name: Ubuntu verification summary
      debug:
        msg:
          - "🎉 Ubuntu 22.04 verification completed!"
          - "✅ PHP {{ php_version_output.stdout.split()[1] }} installed"
          - "✅ WordPress files present"
          - "✅ HTTP responding ({{ http_response.status }})"
          - "🌐 WordPress: http://localhost:8180"