---
name: Publish Role to Ansible Galaxy

on:
  release:
    types: [published]
  workflow_dispatch:  # Permite ejecución manual

jobs:
  deploy:
    name: Deploy Role to Ansible Galaxy
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Publish Role to Galaxy
        run: |
          ansible-galaxy role import \
            --api-key ${{ secrets.GALAXY_API_KEY }} \
            ${{ github.repository_owner }} \
            ${{ github.event.repository.name }}
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}

      - name: Success Notification
        run: |
          echo "🎉 Role published successfully to Ansible Galaxy!"
          echo "📦 Namespace: ${{ github.repository_owner }}"
          echo "🏷️  Role: wordpress_webserver"
          echo "🔗 URL: https://galaxy.ansible.com/${{ github.repository_owner }}/wordpress_webserver"
          echo "📥 Install with: ansible-galaxy role install ${{ github.repository_owner }}.wordpress_webserver"
